name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - name: Get Agent IP
        run: echo "::set-output name=agent_ip::$(curl -s https://api.ipify.org/)"
