name: Get Agent IP
on: [push]

jobs:
  get-agent-ip:
    runs-on: windows-2019
    steps:
    - name: Get Agent IP
      run: |
        $ip = (Invoke-WebRequest -Uri "https://api.ipify.org" -UseBasicParsing).Content
        Write-Output "Agent IP is $ip"
